#!/bin/bash

##   Makes screenshot of the screen or a window, uploads it to the img.fhashtux.org and puts link to the clipboard.
##   Depencies: scrot, xclip, curl and kdialog (or notify-send instead).
## 
##   Written by BrainFucker ( https://github.com/rekcuFniarB/Bash-scripts ).
##   This script is licensed under the GPL3 license.

if [[ $1 == '-h' || $1 == '--help' ]]
  then
    echo "Make screenshot, upload it to the http://www.imageshack.us and put link to the clipboard. Useful with keyboard shortcuts.
    
Usage:
    screenshot
        Makes screenshot of the whole screen.
    screenshot -ub
        Makes screenshot of the current window.
    screenshot -h
    screenshot --help
        Displays this help.
    Also accepts scrot options.

Written by BrainFucker ( https://github.com/rekcuFniarB/Bash-scripts ).
This script is licensed under the GPLv3 license."
    exit 0
fi

cd /tmp

exec scrot "$@" -q 30 -e 'imageshack.us $f; rm $f' '/dev/shm/Screenshot_%s.png'
